### ISSUE TITLE
readme improove

### ISSUE THREAD

**Issue by DmitryOb** [DD1984/rda_cmd#2]
can you add some examples in readme file ?
Im sure that for people who not familiar with "embedded world" but still want burn .img to NAND (like me) it will be helpfully

**Comment by DD1984** [comment]
pls find info on https://4pda.to/forum/index.php?showtopic=813602&st=1060
and see util help
i wrote this utils 4 year ago and nothing remember, and now i have not time to do this job too.
i will very glad if you can write readme file by yourself, and i will add it to this repo

**Comment by DmitryOb** [comment]
I have not permissions to create branches/PR's in this repos, so please commit this updated readme file, maybe it will be useful for someone
[README.md](https://github.com/DD1984/rda_cmd/files/9942452/README.md)

**Comment by DD1984** [comment]
@DmitryOb thank you for your great job
