### ISSUE TITLE
Need help with RDA8810!!!

### ISSUE THREAD

**Issue by Deema35** [DD1984/rda_cmd#3]
Привет!
Я пытаюсь подключить к OrangePI i96 камеру. Но на 10 выводе который питает камеру 2,9В хотя должно быть 1,8В. Я пробовал экспериментировать со всеми регуляторами напряжения никакой реакции. Но при загрузки до того как будет загружен файл "modem.bin" на 10 выводе камеры появляется 1,8В. Но после того как "modem.bin" загружен становится 2,9В и никак не меняется.
Если у тебя доступ к исходникам "modem.bin", или можешь что-нибудь посоветовать, как побороть эти дурацкие 2,9В.

**Comment by DD1984** [comment]
привет, да, такое было - с питанием сд карты - прям точь в точь
да - исходники модема были в общем доступе

**Comment by Deema35** [comment]
На самом деле все регуляторы напряжения просто отправляют команды модему, а он уже управляет напряжениями.

**Comment by Deema35** [comment]
Пока в процессе.

**Comment by Deema35** [comment]
Про мои результаты можно прочитать в этом посте https://4pda.to/forum/index.php?showtopic=813602&view=findpost&p=126862785 Если коротко ничего не получилось.
